### ISSUE TITLE
Bake component 

### ISSUE THREAD

**Issue by seghier** [paireks/dotbimGH#7]
Hi
I add a component to bake the file to Rhino with all attributes and the original guid, the same as Rhino importer.

![image](https://github.com/paireks/dotbimGH/assets/6026588/e3abe553-426b-44aa-9ff3-7543b2fff892)

If you think this is useful i will try to upload the code to this repository

**Comment by paireks** [comment]
I think it's brilliant! 

It's like Elefront in some way :) If you will create a Pull Request I will have a look :)

**Comment by seghier** [comment]
Pull request created 
https://github.com/seghier/dotbimGH

**Comment by paireks** [comment]
Merged
